version: '3.8'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
    container_name: fastapi_app
    ports:
      - "8005:8005"
    environment:
      - SERVICE=fastapi_app
    restart: always
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
    container_name: celery_worker
    environment:
      - SERVICE=celery_worker
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
    container_name: celery_beat
    environment:
      - SERVICE=celery_beat
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
