"""add_dsn_user_event_table

Revision ID: 098cc6ddc2f4
Revises: e36dccf3b597
Create Date: 2025-12-08 17:39:03.251187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '098cc6ddc2f4'
down_revision = 'e36dccf3b597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsn_user_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('remind_datetime', sa.DateTime(), nullable=True),
    sa.Column('remind_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events_events2post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dsn_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsn_user_event_user_id'), 'dsn_user_event', ['user_id'], unique=False)
    op.create_index(op.f('ix_dsn_user_event_event_id'), 'dsn_user_event', ['event_id'], unique=False)
    op.create_unique_constraint('uq_user_event', 'dsn_user_event', ['user_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsn_user_event_event_id'), table_name='dsn_user_event')
    op.drop_index(op.f('ix_dsn_user_event_user_id'), table_name='dsn_user_event')
    op.drop_constraint('uq_user_event', 'dsn_user_event', type_='unique')
    op.drop_table('dsn_user_event')
    # ### end Alembic commands ###
