"""initial_structure

Revision ID: 81c11b41614b
Revises: 
Create Date: 2025-11-28 14:42:21.664128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c11b41614b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exhibitions',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date_before', sa.DateTime(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_exhibitions_post_id'), 'exhibitions', ['post_id'], unique=False)
    op.create_table('bot_user_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('remind_datetime', sa.DateTime(), nullable=True),
    sa.Column('remind_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events_events2post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bot_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_user_events_id'), table_name='bot_user_events')
    op.drop_table('bot_user_events')
    op.drop_index(op.f('ix_exhibitions_post_id'), table_name='exhibitions')
    op.drop_table('exhibitions')
    op.drop_table('bot_user')
    op.drop_index(op.f('ix_bot_events_id'), table_name='bot_events')
    op.drop_table('bot_events')
    op.drop_index(op.f('ix_api_request_log_id'), table_name='api_request_log')
    op.drop_table('api_request_log')
    # ### end Alembic commands ###
