name: Basic CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

      env:
        TIMEPAD_TOKEN: ${{ secrets.TIMEPAD_TOKEN }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        DEV_CHANNEL_ID: ${{ secrets.DEV_CHANNEL_ID }}
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
        VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
        VK_DEV_GROUP_ID: ${{ secrets.VK_DEV_GROUP_ID }}
        VK_USER_ID: ${{ secrets.VK_USER_ID }}


    - name: Lint with flake8
      run: |
        echo "Running flake8..."
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Check formatting with black
      run: |
        echo "Checking code format with black..."
        black --check .

    - name: Check import sorting with isort
      run: |
        echo "Checking import order with isort..."
        isort . --check-only
        
    - name: Run tests with pytest
      run: pytest