name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: secrethub/actions/env-export@v0.2.1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make install
    - name: Code style
      run: |
        make lint_check
    - name: Test with pytest
      run: |
        make test

  deploy:
    needs: testing
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        make deploy
