name: Test & deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make install
    - name: Code style
      run: |
        make lint_check
    - name: Test with pytest
      env:
        TIMEPAD_TOKEN: ${{ secrets.TIMEPAD_TOKEN }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        DEV_CHANNEL_ID: ${{ secrets.DEV_CHANNEL_ID }}
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
        VK_ALBUM_ID: ${{ secrets.VK_ALBUM_ID }}
        VK_DEV_ALBUM_ID: ${{ secrets.VK_DEV_ALBUM_ID }}
        VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
        VK_DEV_GROUP_ID: ${{ secrets.VK_DEV_GROUP_ID }}
        VK_USER_ID: ${{ secrets.VK_USER_ID }}
      run: |
        make test

  deploy:
    needs: testing
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        make deploy
