name: Test & deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: self-hosted
    steps:
    - name: Setup test environ
      run: pip install tox

  lint:
    needs: setup
    runs-on: self-hosted
    steps:
    - name: Lint
      run: tox -e lint

  test:
    needs: lint
    runs-on: self-hosted
    steps:
    - name: Test
      run: tox -e test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: make deploy
