name: Test & deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run: make setup_python

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Lint
      run: |
        make install_dev_tools
        make lint_check

  test:
    needs: lint
    runs-on: self-hosted
    steps:
    - name: Test with pytest
      env:
        TIMEPAD_TOKEN: ${{ secrets.TIMEPAD_TOKEN }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        DEV_CHANNEL_ID: ${{ secrets.DEV_CHANNEL_ID }}
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
        VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
        VK_DEV_GROUP_ID: ${{ secrets.VK_DEV_GROUP_ID }}
        VK_USER_ID: ${{ secrets.VK_USER_ID }}
      run: |
        make install
        make install_dev_tools
        make test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        make install
        make deploy
